[package]
name = "interface"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0.219"
thiserror = "2.0.12"
bayesplay = { path = "../bayesplay" }
serde_json = "1.0.140"
dict_derive = "0.6.0"
pyo3 = "0.24.1"

